spring.main.allow-bean-definition-overriding=true

azure.cosmos.uri=${COSMOS_DATASOURCE_URL}
azure.cosmos.key=${COSMOS_DATASOURCE_KEY}
azure.cosmos.database=${COSMOS_DATASOURCE_NAME}

azure.cosmos.source-container=${COSMOS_CONTAINER_SOURCE}
azure.cosmos.target-container=${COSMOS_CONTAINER_TARGET}
azure.cosmos.lease-container=${COSMOS_CONTAINER_LEASE}

retry.max-attempts=${RETRY_MAX_ATTEMPTS:5}
retry.backoff-seconds=${RETRY_BACKOFF:5}